// src/app/components/dashboard/dashboard.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { filter, fromEvent, interval, Subscription, tap, timeInterval } from 'rxjs';
import { DEFAULT_REFRESH_RATE } from 'src/app/shared/const';

@Component({
  selector: 'app-dashboard',
  template: `
    <div class="dashboard">
      <div class="dashboard-body">
        <div class="container">
          <app-info-top></app-info-top>
          <img src="/assets/images/map.png" class="map" />
          <app-info-map></app-info-map>
          <app-info-bottom></app-info-bottom>
          <app-rpm-gauge [value]="rpm"></app-rpm-gauge>
          <app-speed-gauge [value]="speed"></app-speed-gauge>
        </div>
      </div>
    </div>
  `
})
export class DashboardComponent implements OnInit, OnDestroy {
  sub = new Subscription();
  acc = false;
  rpm = 0;
  speed = 0;

  constructor() { }

  ngOnInit(): void {
    const keyDown$ = fromEvent<KeyboardEvent>(document, 'keydown')
      .pipe(
        filter((e: KeyboardEvent) => e.key === 'ArrowUp'),
        tap(() => this.acc = true)
      );

    const keyUp$ = fromEvent<KeyboardEvent>(document, 'keyup')
      .pipe(
        filter((e: KeyboardEvent) => e.key === 'ArrowUp'),
        tap(() => this.acc = false)
      );

    const interval$ = interval(DEFAULT_REFRESH_RATE)
      .pipe(
        timeInterval(),
        tap(() => {
          if (this.acc) {
            this.speed = this.speed < 300 ? this.speed += 1 : this.speed;
            this.rpm = this.rpm < 6000 ? this.rpm += 50 : this.rpm;
          } else {
            this.speed = this.speed > 0 ? this.speed -= 1 : this.speed;
            this.rpm = this.rpm > 0 ? this.rpm -= 50 : this.rpm;
          }
        })
      );

    this.sub.add(...[
      keyDown$.subscribe(),
      keyUp$.subscribe(),
      interval$.subscribe()
    ]);
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }
}

// src/components/Dashboard/Dashboard.tsx
import * as React from 'react';
import { fromEvent, interval, Subscription } from 'rxjs';
import { filter, timeInterval } from 'rxjs/operators';

import { InfoBottom } from '../InfoBottom/InfoBottom';
import { InfoMap } from '../InfoMap/InfoMap';
import { InfoTop } from '../InfoTop/InfoTop';
import { RpmGauge } from '../RpmGauge/RpmGauge';
import { SpeedGauge } from '../SpeedGauge/SpeedGauge';

interface IDashboardState {
  acc: boolean;
  rpm: number;
  speed: number;
}

export class Dashboard extends React.Component<{}, IDashboardState> {
  private subs: Subscription;

  constructor(props: {}) {
    super(props);

    this.state = {
      acc: false,
      rpm: 0,
      speed: 0
    };
  }

  public componentDidMount() {
    this.subs = new Subscription();

    const keyDown = fromEvent(document, 'keydown')
      .pipe(filter((e: KeyboardEvent) => e.which === 38))
      .subscribe(() => this.setState({ acc: true }));

    const keyUp = fromEvent(document, 'keyup')
      .pipe(filter((e: KeyboardEvent) => e.which === 38))
      .subscribe(() => this.setState({ acc: false }));

    const keyInterval = interval(10)
      .pipe(timeInterval())
      .subscribe(() => {
        if (this.state.acc) {
          if (this.state.speed < 300) {
            this.setState({ speed: this.state.speed + 1 });
          }
          if (this.state.rpm < 6000) {
            this.setState({ rpm: this.state.rpm + 50 });
          }
        } else {
          if (this.state.speed > 0) {
            this.setState({ speed: this.state.speed - 1 });
          }
          if (this.state.rpm > 0) {
            this.setState({ rpm: this.state.rpm - 50 });
          }
        }
      });

    this.subs.add(keyDown).add(keyUp).add(keyInterval);
  }

  public componentWillUnmount() {
    this.subs.unsubscribe();
  }

  public render() {
    return (
      <div className="dashboard">
        <div className="dashboard-body">
          <div className="container">
            <InfoTop />
            <img src="/images/map.png" className="map" />
            <InfoMap />
            <InfoBottom />
            <RpmGauge value={this.state.rpm} />
            <SpeedGauge value={this.state.speed} />
          </div>
        </div>
      </div>
    );
  }

  private handleKeyDown(e: KeyboardEvent): void {
    if (e.which === 38) {
      this.setState({ acc: true });
    }
  }

  private handleKeyUp(e: KeyboardEvent): void {
    if (e.which === 38) {
      this.setState({ acc: false });
    }
  }
}
